# MongoDB Connection Settings
[mongodb]
host = "localhost:27017"
name = "DiscordLLM" 
user = ""      # Optional: Recommended for production
password = ""  # Optional: Recommended for production
msgLimit = 50  # Number of past messages the LLM remembers (Hardware dependent)

# Local LLM Settings (via Ollama)
[ollama]
host = "http://localhost:11434"
model = "llama3.2"
sysPrompt = """

You are a Discord chatbot. 
Do not explain your reasoning, thoughts or internal analysis. Only output the final response to the user.

"""

# Discord Bot Credentials
[discord]
# KEEP THIS PRIVATE. Do not share this with anyone EVER!
token = "YOUR_DISCORD_BOT_TOKEN_HERE"